// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC1i-Dm8jiBH-4IiP14Ubl1uxbxG1d3p4',
    appId: '1:700665619392:web:cf5ceb5ea65d8b19b19e25',
    messagingSenderId: '700665619392',
    projectId: 'chat-app-49bf2',
    authDomain: 'chat-app-49bf2.firebaseapp.com',
    storageBucket: 'chat-app-49bf2.appspot.com',
    measurementId: 'G-7JMZS3T43R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmxjxJrnMhbQnonIv66_7Bz-EGONs8W_I',
    appId: '1:700665619392:android:ddf5a348ffb07db0b19e25',
    messagingSenderId: '700665619392',
    projectId: 'chat-app-49bf2',
    storageBucket: 'chat-app-49bf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOt1rNOuLWIUc5rOJgD7QJftidNXU53uE',
    appId: '1:700665619392:ios:0940ece0b8c1a9d4b19e25',
    messagingSenderId: '700665619392',
    projectId: 'chat-app-49bf2',
    storageBucket: 'chat-app-49bf2.appspot.com',
    iosClientId: '700665619392-r196okiv73qgiddd4amm38bq27sdea8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOt1rNOuLWIUc5rOJgD7QJftidNXU53uE',
    appId: '1:700665619392:ios:4c0868651d98660eb19e25',
    messagingSenderId: '700665619392',
    projectId: 'chat-app-49bf2',
    storageBucket: 'chat-app-49bf2.appspot.com',
    iosClientId: '700665619392-v59pes9p1g0akanr20guuocml430j1bl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
